"""
Django settings for facefake project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

import mongoengine

from facefake import modelrouter

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$n371j#d*5$mpcu5)v)7vpnj%qn79v+%(+h(034m!eqe_!v8bh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TEMPLATE_DEBUG = DEBUG
ALLOWED_HOSTS = []

ADMINS = (
    # ('Your Name', 'your_email@example.com'),
)

MANAGERS = ADMINS
# Application definition

# MongoDB settings
MONGODB_DATABASES = {
    'default': {'name': 'face_fake'}
}
DJANGO_MONGOENGINE_OVERRIDE_ADMIN = True

SESSION_ENGINE = 'django_mongoengine.sessions'

# # setup connect to database Mongodb
# _MONGODB_USER = 'admin'
# _MONGODB_PASSWD = 'hoada921'
# _MONGODB_HOST = 'localhost:27017'
# _MONGODB_NAME = 'facefake'
# _MONGODB_DATABASE_HOST = 'mongodb://%s:%s@%s/%s' % (_MONGODB_USER, _MONGODB_PASSWD, _MONGODB_HOST, _MONGODB_NAME)
# mongoengine.connect(_MONGODB_NAME, host=_MONGODB_DATABASE_HOST)

DATABASE_ROUTERS = ['facefake.modelrouter.DatabaseAppsRouter', ]
DATABASE_APPS_MAPPING = {'no_sql': 'no_sql'}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'facefake_project',
        'USER': 'root',
        'PASSWORD': 'hoada921',
        'HOST': '127.0.0.1',
        'PORT': '3306', },
    'no_sql': {
        'ENGINE': 'django.db.backends.dummy',
    }
}
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.user',
    'app.friend',
    'app.status',
    'app.likes',
    'app.comments',
    # 'django_mongoengine.mongo_auth',
    # 'django_mongoengine.mongo_admin.sites',
    # 'django_mongoengine.mongo_admin',

)

INTERNAL_IPS = ('127.0.0.1', '10.0.2.2',)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'facefake.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'facefake.wsgi.application'





# Use MongoEngine's User
# AUTHENTICATION_BACKENDS = ('mongoengine.django.auth.MongoEngineBackend',)

AUTHENTICATION_BACKENDS = (
    'django_mongoengine.mongo_auth.backends.MongoEngineBackend',
)

# Hack the test runner
TEST_RUNNER = 'yourproject.tests.NoSQLTestRunner'
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_ID = 1

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

MEDIA_URL = '/media/'

AVATAR_DIR = 'avatar'
